### ISSUE TITLE
Error en qgis

### ISSUE THREAD

**Issue by dayanaa2727** [Giswater/giswater_dbmodel#18]
hola, al cargar un archivo con extension inp en qgis con giswater, me genera esta nota: 

INSERT INTO vi_timeseries SELECT csv1::character varying, csv2::character varying, csv3:: character varying, csv4:: numeric 
FROM temp_csv where source like '%[TIMESERIES]%' 
                                                                             AND fid=239 AND (csv1 NOT LIKE '[% AND csv1 NOT LIKE';%') AND cur_user='postgres' 
ORDER BY id>> 
función PL/pgSQL gw_fct_importswmm_inp(json) en la línea 434 en execute
no se puede insertar en la vista <<vi_timeseries>>

**Comment by albertbofill** [comment]
Hola @dayanaa2727 
Había un error, pues en la vista vi_timeseries no existía trigger para permitir la inserción de datos.
Acabamos de repararlo en el repositorio dónde está la versión 3.5.034. Puedes desinstal·lar y reinstal·lar el plugin de nuevo para volver a probar: https://download.giswater.org/plugin/3.5/giswater.xml
