### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by dayanaa2727** [Giswater/giswater_dbmodel#19]
expresión SQL <<NEW.date ilike 'FILE'>>
función PL/pgSQL gw_trg_vi() en la línea 285 en IF
sentencia SQL: <<INSERT INTO vi_timeseries SELECT csv1::character varying, csv2::charcater varying, csv3:: character varying, csv::numeric FROM temp_csv where source like '%[TIMESERIES]%' 
AND fis=239 AND (csv1 NOT LIKE '[%' AND csv1 NOT LIKE ';%') AND cur_user='postgres' 
ORDER BY id>>
función PL/pgsql gw_fct_import_swmm_inp(json) en la línea 434 en EXECUTE 
el registro <<new>> no tiene un campo <<date>>

**Comment by albertbofill** [comment]
Solved on commit https://github.com/Giswater/giswater_dbmodel/commit/576eef693e6e1d056aca71400d7336ab99925cee
