### ISSUE TITLE
Pattern export precision

### ISSUE THREAD

**Issue by jcpiriou** [Giswater/giswater_dbmodel#23]
Hello all,
I have a case study where I use a big precision for pattern (level pattern for water drilling in cm). Pattern factors in table inp_pattern_value are of a type numeric (12,4), that is not enough for these cases. Should it be possible to change the type to get more precision in export?
Best!

**Comment by edgarfuste** [comment]
Hi @jcpiriou ,
We have added in the TODO to modify the column type according to your issue, for release 3.6.009. 
In case you are in a hurry for this change, you can proceed to make the change yourself in your environment. For this you should do for the tables "inp_pattern_value" and "rpt_inp_pattern_value":

ALTER TABLE table_name ALTER COLUMN column_name TYPE numeric(12, 6);

You will get an error that some views depend on this table, you should save in a .txt the ddl of those views that give you problems, delete them and after making the ALTER COLUMN recreate the views.

Regarts.

**Comment by jcpiriou** [comment]
Thanks Edgar. Already done in my environnement, but I wanted it to be pushed in the mainline. Best

**Comment by edgarfuste** [comment]
Perfect @jcpiriou , we will apply the changes in the release.
Thanks!
