### ISSUE TITLE
index insertion 

### ISSUE THREAD

**Issue by jcpiriou** [Giswater/giswater_dbmodel#8]
Hello
in 3.5.022 version, when having mass inserted values in node and arc, I was trying to create new nodes from QGIS but the sequence of the table node still bigin with initial values so there is an error (node_id is existing). 
I did not have this issue before.
I make a correction to restart urn_id_seq with max node_id/arc_id but I wonder if it should not be better to have 2 differents sequences for nodes and arcs.
What do you think about it?

**Comment by xtorret** [comment]
Hello @jcpiriou
The official and released version is 3.5.020.
If you are looking to use 2.5.022 you are very welcomed to do it, but you need to merge both github repositories (giwater_qgis_plugin + giswater_dbmodel) to work with
On the other hand next week will re released the 3.5.023 (wich will be the new official one)

**Comment by jcpiriou** [comment]
Was talking about official version 3.2.020 sorry. I will check new version 3.5.023 next week: is there some modification on the issue I was talking about?

**Comment by xtorret** [comment]
yes, it is solved!

**Comment by jcpiriou** [comment]
Great! Thanks Xavier. See you
